# Generated by Django 5.2.12 on 2026-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_one_day_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
